name: rotatable_overlay
description: A flutter widget that makes its child rotatable by dragging around its center
version: 0.0.6
repository: https://github.com/daniel-riffi/rotatable_overlay

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  angle_utils: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
